name: 'Vercel Status Checks'

on:
  push:
    branches:
      - main

jobs:
  notify-vercel:
    name: 'Notify Vercel of new commit'
    runs-on: ubuntu-latest
    steps:
      - name: 'Dispatch lint check to Vercel'
        uses: 'vercel/repository-dispatch/actions/status@v1'
        with:
          name: 'Vercel - techshackapp: lint'
          token: ${{ secrets.GITHUB_TOKEN }}
